### ISSUE TITLE
Error : lexical error: invalid char in json text.

### ISSUE THREAD

**Issue by stevesteve2** [benjaminguinaudeau/tiktokr#11]
When I call many of the functions, for example: 

user_posts <- tk_posts(scope = "user", query = "steverathje", n = 1000)

I get the following error: 

Error : lexical error: invalid char in json text.
                                       illegal request...
                     (right here) ------^

This was working about a week or so ago, and now it does not. 

Thank you, and excellent package.

**Comment by adamkthecoder** [comment]
I'm also getting this message! Not sure why.

**Comment by stevesteve2** [comment]
Did something change in the TikTok API? The package was working great a week or so ago and now it doesn't...

**Comment by benjaminguinaudeau** [comment]
I'm also getting the message. The Tiktok API seems to have changed at least for the user endpoint. 

I need to investigate a bit more to see which endpoints are affected and to, eventually, fix this. I will look into it by the end of this week. Hopefully, I will push an update fixing the issue.

I'll keep you updated, once I've found the issue.

**Comment by stevesteve2** [comment]
Thank you! I love your package by the way, thank you for making it. I was hoping to make an R Shiny app using it where users can visualize their TikTok data.

**Comment by benjaminguinaudeau** [comment]
That's very good to hear! Thank you! 

An app to monitor data sounds like a great idea! I hope I will be able to fix it soon so that it won't delay too much your shiny app :)

**Comment by stevesteve2** [comment]
Thanks, and no worries! :)

**Comment by benjaminguinaudeau** [comment]
Hi Steve, 

So I've fixed most endpoints. I pushed a temporary commit with all fixes, but I'll work tomorrow on the documentation and the last missing endpoint (the comment one). You should be able to tk_info for hashtag, user, music, and posts as well as tk_posts for hashtags, music, trends, and users. Let me know if that works well. 

Tiktok changed indeed its API and now transmits most user data as query parameters in the URL instead of HTTP headers. They did not increase security at all, which let me think that we still have time ahead of us before they shut down their API. 

If you have any requests, let me know; I'm glad to implement what's doable or improve any aspect of the current package.

**Comment by stevesteve2** [comment]
Thanks so much for the quick fix! It works now from taking a quick look. 

That's cool their API is still open. As a big user of rtweet, and since TikTok is taking over the social media sphere, this is an awesome package for getting broader social media data. 

No requests now, mostly because I don't know what the API is capable of (for instance I don't know if a get_followers function is possible) but I'll let you know how things progress. :)

**Comment by benjaminguinaudeau** [comment]
Great! I'll close the issue then! Don't hesitate to contact me if you have any questions or suggestions! Until then, enjoy the data ;)
